### ISSUE TITLE
[RFC] Disable filtering in widgets

### ISSUE THREAD

**Issue by Clebal** [CartoDB/carto-react#195]
### Issue

Currently, in both widget and widget ui there isn't a way to disable filtering/category selection.

### Solution

Add a property called: `filtering` or `interactivity` in every widget, with true by default, that allows to have static widgets if false.

### Why do I need that?

In professional services projects it's a common use case where we need to show static widgets once we've made an analysis and we don't want the user to change the filters already applied.

**Comment by VictorVelarde** [comment]
I think this makes a lot of sense. To be honest I think that we already had this feature on (I think we had it in the past).

**Comment by borja-munoz** [comment]
I've already talked with @josegilg and we just need to make some minor changes to the widgets design, so the RFC is approved for implementation.
